title: Christian Schetsche # your name (or website title) here
logo: "/images/IMG-20210725-WA0009.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly skilled and versatile professional with a strong academic background in business sciences, a master's degree in tourism management and planning, and a forthcoming Ph.D. in psychology. With over 10 years of experience in hotel commercial management, I have successfully led teams, developed sales strategies, and consistently achieved commercial objectives. Additionally, I have an outstanding track record of 10 years as a German language instructor and 2 years as a university professor of statistics. As the first author of over 20 publications in Scopus-indexed journals, I have demonstrated my ability to conduct research and effectively communicate findings. I have also developed technical skills in data analysis and programming, showcased by the creation of a web application for data analysis. I am passionate about data science and excited to apply my skills and knowledge in this rapidly evolving field. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
